import assert from 'node:assert/strict';
import {autoQuality,playbackPlan,videoPoint} from './stream-policy.mjs';
assert.deepEqual(playbackPlan({begin:0,end:2,currentTime:0}),{seek:1.65,rate:1});
assert.equal(playbackPlan({begin:0,end:.45,currentTime:0}).rate,1);
assert.equal(playbackPlan({begin:1,end:1.1,currentTime:0}).seek,1);
assert.deepEqual(playbackPlan({begin:0,end:.2,currentTime:0}),{seek:null,rate:1});
const good={receiverVisible:true,decodedFps:30,targetFps:30,intervalSeconds:1,bufferMs:180,framesInInterval:30,dropsInInterval:0};
const state={};
for(let n=0;n<29;n++)assert.equal(autoQuality('low',good,state,n*1000),null);
assert.equal(autoQuality('low',good,state,30000),'balanced');
for(let n=0;n<30;n++)assert.equal(autoQuality('balanced',good,state,31000+n*1000),null,'No rapid up/down oscillation');
const poor={...good,bufferMs:900};
for(let n=0;n<2;n++)assert.equal(autoQuality('balanced',poor,state,70000+n*1000),null);
assert.equal(autoQuality('balanced',poor,state,72000),'low');
for(let n=0;n<40;n++)assert.equal(autoQuality('low',{...good,receiverVisible:false},state,180000+n*1000),null,'Hidden tabs cannot authorize upgrades');
assert.equal(autoQuality('low',{...good,decodedFps:null},state,250000),null);
assert.equal(autoQuality('unknown',good,state,250000),null);
const rect={left:100,top:50,width:1000,height:1000};
assert.deepEqual(videoPoint(rect,1280,720,600,550),{x:640,y:360,inside:true});
assert.equal(videoPoint(rect,1280,720,600,100).inside,false,'Letterbox areas cannot issue orders');
assert.deepEqual(videoPoint(rect,1280,720,1500,550),{x:1279,y:360,inside:false});
assert.equal(videoPoint(rect,0,720,0,0),null);
console.log('Playback catch-up, gradual auto quality, cooldown, hidden/missing samples and letterboxed input checks passed.');
