const {chromium}=require('playwright');
const fs=require('node:fs/promises');const path=require('node:path');const assert=require('node:assert/strict');
(async()=>{
 const report={version:'2.1.0',checks:[],errors:[],missing:[],started:new Date().toISOString(),scope:'Disposable Windows Chrome profile; real local archives and threaded-engine gameplay'};
 await fs.mkdir('output/playwright',{recursive:true});
 report.profile=`.local/version-21-browser-${Date.now()}`;
 const context=await chromium.launchPersistentContext(path.resolve(report.profile),{channel:'chrome',headless:true,acceptDownloads:true,viewport:{width:1440,height:900}});
 const page=await context.newPage();for(const previous of context.pages())if(previous!==page)await previous.close();let game;
 page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.status()===404)report.missing.push(r.url())});
 const timer=setInterval(()=>console.log('V2.1',report.stage),20000);
 const wait=async(label,fn,predicate,timeout=60000)=>{const deadline=Date.now()+timeout;let value;while(Date.now()<deadline){value=await fn();if(predicate(value))return value;await page.waitForTimeout(250)}throw Error(`${label} timed out: ${JSON.stringify(value).slice(0,1000)}`)};
 const rpc=(command,payload={})=>game.evaluate(([command,payload])=>window.CnCPort.rpc(command,payload),[command,payload]);
 const library=()=>page.evaluate(()=>window.ZeroHAssetLibrary.installedLibrary());
 const launch=async()=>{await page.locator('#solo').click();await page.waitForFunction(()=>document.getElementById('gameFrame').contentWindow?.document.getElementById('loading')?.hidden===true,null,{timeout:180000});game=page.frames().find(f=>f.url().includes('/harness/game.html'));await wait('Website ready',()=>page.locator('#gameStatus').textContent(),s=>s.includes('Choose Single Player'));await wait('Skirmish ready',()=>rpc('queryWindowByName',{name:'SkirmishGameOptionsMenu.wnd:ButtonStart'}),r=>r.result?.clickable===true);};
 const clickNative=async name=>{await wait(name,async()=>{const query=await rpc('queryWindowByName',{name});const frame=await rpc('realEngineFrame',{frames:1});const state=frame.frame?.clientState;if(query.result?.clickable&&state?.transition?.finished&&state?.mainMenu?.debug?.dontAllowTransitions===0)return rpc('clickWindowByName',{name});return query},r=>r.ok===true&&r.command==='clickWindowByName');};
 try{
  report.stage='Interface, diagnostics and updates';await page.goto('http://localhost:8094/');await page.waitForFunction(()=>typeof document.getElementById('nameForm').onsubmit==='function');
  if(await page.locator('#entry').isVisible()){await page.locator('#name').fill('V21Test');await page.locator('#nameForm button').click()}
  await page.locator('#openSettings').click();assert.equal(await page.locator('#appVersion').textContent(),'Installed interface: 2.1.0');await page.locator('#checkUpdates').click();await wait('Version check',()=>page.locator('#updateStatus').textContent(),s=>s.includes('current'));
  await page.screenshot({path:'output/playwright/v21-settings-desktop.png'});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'output/playwright/v21-settings-mobile.png'});await page.setViewportSize({width:1440,height:900});
  let download=page.waitForEvent('download');await page.locator('#settingsDiagnostics').click();let file=await download;try{await file.saveAs('.local/v21-diagnostics.json')}catch(e){report.downloadFailure={url:file.url(),failure:await file.failure().catch(error=>error.message),pageClosed:page.isClosed(),pages:context.pages().length};throw e}let diagnostic=JSON.parse(await fs.readFile('.local/v21-diagnostics.json'));assert.equal(diagnostic.version,'2.1.0');assert.ok(Array.isArray(diagnostic.recentErrors));
  await context.grantPermissions(['clipboard-read','clipboard-write']);await page.locator('#copyDiagnostics').click();await wait('Copy diagnostics',()=>page.locator('#settingsStatus').textContent(),s=>s.includes('copied'));assert.equal(JSON.parse(await page.evaluate(()=>navigator.clipboard.readText())).version,'2.1.0');await page.locator('#closeSettings').click();
  report.checks.push('Version check, downloadable/copyable browser diagnostics, desktop/mobile settings without overflow');
  report.stage='Real folder import';
  if(await page.locator('#lobby').isVisible()){if(!await page.locator('#removeLibrary').isVisible())await page.locator('#libraryDetails summary').click();await page.locator('#removeLibrary').click();await page.locator('#confirmProceed').click();await page.locator('#setup').waitFor({state:'visible'});}
  await page.locator('#folderInput').setInputFiles('.local/packaging/Zero-Hour-Browser-English');await page.locator('#lobby').waitFor({state:'visible',timeout:240000});const initial=await library();assert.equal(initial.archives.length,17);
  await page.evaluate(async()=>{
    const root=await navigator.storage.getDirectory();const saves=await root.getDirectoryHandle('v21-saved-data',{create:true});const writer=await(await saves.getFileHandle('keep.txt',{create:true})).createWritable();await writer.write('stored-save-sentinel');await writer.close();
    const native=await Object.getPrototypeOf(navigator.storage).getDirectory.call(navigator.storage);const other=await native.getDirectoryHandle('v21-other-product',{create:true});const out=await(await other.getFileHandle('keep.txt',{create:true})).createWritable();await out.write('other-product-sentinel');await out.close();
  });
  if(!await page.locator('#removeLibrary').isVisible())await page.locator('#libraryDetails summary').click();
  report.stage='Failed deletion preserves installation';
  await page.evaluate(root=>{const name=root.split('/').at(-1),original=FileSystemDirectoryHandle.prototype.removeEntry;window.__v21RestoreRemoval=()=>FileSystemDirectoryHandle.prototype.removeEntry=original;FileSystemDirectoryHandle.prototype.removeEntry=function(entry,options){if(entry===name)return Promise.reject(new DOMException('Simulated permission failure','NotAllowedError'));return original.call(this,entry,options)}},initial.root);
  await page.locator('#removeLibrary').click();await page.locator('#confirmProceed').click();await wait('Failed removal',()=>page.locator('#error').textContent(),s=>s.includes('Simulated permission failure'));assert.equal((await library()).root,initial.root);await page.evaluate(()=>window.__v21RestoreRemoval());
  report.stage='Real browser removal';await page.locator('#removeLibrary').click();await page.locator('#confirmProceed').click();await page.locator('#setup').waitFor({state:'visible'});assert.equal(await library(),null);
  assert.equal(await page.evaluate(async root=>{try{const d=await(await navigator.storage.getDirectory()).getDirectoryHandle('cnc-library');await d.getDirectoryHandle(root.split('/').at(-1));return false}catch(e){return e.name==='NotFoundError'}},initial.root),true);
  await page.reload();await page.locator('#setup').waitFor({state:'visible'});assert.equal(await page.locator('#commander').textContent(),'V21Test');
  const sentinels=()=>page.evaluate(async()=>{const root=await navigator.storage.getDirectory(),native=await Object.getPrototypeOf(navigator.storage).getDirectory.call(navigator.storage);const read=async(d,n)=> (await(await(await d.getDirectoryHandle(n)).getFileHandle('keep.txt')).getFile()).text();return {save:await read(root,'v21-saved-data'),other:await read(native,'v21-other-product')}});
  assert.deepEqual(await sentinels(),{save:'stored-save-sentinel',other:'other-product-sentinel'});report.checks.push('Deletion failure retains manifest; real removal deletes archives; reload preserves commander, stored-data sentinel and another product');
  report.stage='ZIP reimport and remembered installation';await page.locator('#archiveInput').setInputFiles('.local/packaging/Zero-Hour-Browser-English.zip');await page.locator('#lobby').waitFor({state:'visible',timeout:600000});const current=await library();assert.equal(current.archives.length,17);await page.reload();await page.locator('#lobby').waitFor({state:'visible'});assert.equal((await library()).root,current.root);
  report.stage='Cancelled replacement and bad archive';await page.locator('#libraryDetails summary').click();await page.locator('#replaceLibrary').click();await page.locator('#archiveInput').setInputFiles('.local/packaging/Zero-Hour-Browser-English.rar');await page.locator('#cancelImport').waitFor({state:'visible'});await page.locator('#cancelImport').click();await wait('Cancel finishes',()=>page.locator('#chooseArchive').isEnabled(),Boolean);assert.equal((await library()).root,current.root);
  await page.locator('#archiveInput').setInputFiles({name:'broken.zip',mimeType:'application/zip',buffer:Buffer.from('not a zip')});await wait('Invalid import finishes',()=>page.locator('#chooseArchive').isEnabled(),Boolean);assert.equal((await library()).root,current.root);await page.locator('#backToLibrary').click();await page.locator('#lobby').waitFor({state:'visible'});
  report.checks.push('Actual ZIP reimport, remembered files, cancelled RAR and malformed ZIP preserve previous installation');
  report.stage='Leftover cleanup and active-tab protection';
  await page.evaluate(async()=>{
    const root=await navigator.storage.getDirectory();for(const [parent,name]of [['cnc-library','install-v21-orphan'],['cnc-archives','ns-v21-123'],['archive-staging','extract-v21-stale'],['archive-staging','extract-v21-active']])await(await root.getDirectoryHandle(parent,{create:true})).getDirectoryHandle(name,{create:true});
    await new Promise(resolve=>{navigator.locks.request('zhweb-extract:extract-v21-active',()=>{resolve();return new Promise(release=>window.__v21ReleaseExtract=release)})});
  });
  if(!await page.locator('#cleanStorage').isVisible())await page.locator('#libraryDetails summary').click();await page.locator('#cleanStorage').click();await wait('Cleanup finishes',()=>page.locator('#maintenanceStatus').textContent(),s=>s.includes('another tab'));assert.equal((await library()).root,current.root);
  const leftovers=await page.evaluate(async()=>{const root=await navigator.storage.getDirectory();const exists=async(parent,name)=>{try{await(await root.getDirectoryHandle(parent)).getDirectoryHandle(name);return true}catch{return false}};return {orphan:await exists('cnc-library','install-v21-orphan'),runtime:await exists('cnc-archives','ns-v21-123'),stale:await exists('archive-staging','extract-v21-stale'),active:await exists('archive-staging','extract-v21-active')}});assert.deepEqual(leftovers,{orphan:false,runtime:false,stale:false,active:true});await page.evaluate(()=>window.__v21ReleaseExtract());
  await page.evaluate(async root=>{await new Promise(resolve=>{navigator.locks.request('cnc-port-opfs-install:'+root.split('/').at(-1),{mode:'shared'},()=>{resolve();return new Promise(release=>window.__v21ReleaseGame=release)})})},current.root);
  await page.locator('#removeLibrary').click();await page.locator('#confirmProceed').click();await wait('Active root protected',()=>page.locator('#error').textContent(),s=>s.includes('in use'));assert.equal((await library()).root,current.root);await page.evaluate(()=>window.__v21ReleaseGame());assert.deepEqual(await sentinels(),{save:'stored-save-sentinel',other:'other-product-sentinel'});report.checks.push('Cleanup removes stale install/runtime/extraction roots, preserves active roots and other product data; active installation removal blocked');
  await page.evaluate(()=>{window.__v21Shutdown=[];window.addEventListener('message',e=>{if(e.origin===location.origin&&e.data.type==='zh-exited')window.__v21Shutdown.push(e.data)})});
  report.stage='Native Exit Game';await launch();await clickNative('SkirmishGameOptionsMenu.wnd:ButtonBack');await clickNative('MainMenu.wnd:ButtonExit');await page.locator('#gameView').waitFor({state:'hidden',timeout:60000});report.nativeExit=await page.evaluate(()=>window.__v21Shutdown.at(-1));assert.ok(report.nativeExit);assert.equal(report.nativeExit.shutdown.close.finalSaveFresh,true);assert.equal(report.nativeExit.warning,undefined);assert.equal((await library()).root,current.root);report.checks.push('Native Exit Game returns to launcher with confirmed save flush and shutdown');
  report.stage='Real skirmish, resizing and diagnostics';await launch();await rpc('realEngineSetSkirmishMap',{mapName:'maps/alpine assault/alpine assault.map'});await rpc('realEngineSetSkirmishLocalTemplate',{templateName:'FactionGLA'});await rpc('clickWindowByName',{name:'SkirmishGameOptionsMenu.wnd:ButtonStart'});
  await wait('Actual battlefield',()=>rpc('realEngineFrame',{frames:1}),r=>r.frame?.clientState?.gameplay?.inGame&&!r.frame?.clientState?.gameplay?.loadingMap&&r.frame?.clientState?.gameplay?.objectCount>0,180000);
  await game.locator('#viewport').press('F8');if(!await page.locator('#gameBar').isVisible())await game.locator('#viewport').press('F8');await page.locator('#gameSettings').click();await page.locator('#resolution').selectOption('1600x900');await wait('Live resize',()=>rpc('threadedStatus'),r=>r.status?.engineDisplaySize?.width===1600);
  download=page.waitForEvent('download');await page.locator('#settingsDiagnostics').click();file=await download;await file.saveAs('.local/v21-engine-diagnostics.json');diagnostic=JSON.parse(await fs.readFile('.local/v21-engine-diagnostics.json'));assert.equal(diagnostic.engine.version,'2.1.0');assert.equal(diagnostic.engine.display.width,1600);assert.ok(diagnostic.recentErrors.length>0);
  await page.route('**/version.json',route=>route.fulfill({json:{version:'2.2.0'}}));await page.locator('#checkUpdates').click();await wait('Update found',()=>page.locator('#applyUpdate').isVisible(),Boolean);await page.locator('#applyUpdate').click();assert.equal(await page.locator('#gameView').isVisible(),true);assert.match(await page.locator('#updateStatus').textContent(),/Exit the game/);await page.unroute('**/version.json');await page.locator('#closeSettings').click();
  await page.screenshot({path:'output/playwright/v21-battlefield.png'});report.renderer=(await rpc('threadedStatus')).status?.graphics?.renderer;
  report.stage='Protected toolbar exit and relaunch';if(!await page.locator('#gameBar').isVisible())await game.locator('#viewport').press('F8');await page.locator('#exitGame').click();await page.locator('#confirmAction').waitFor({state:'visible'});await page.locator('#confirmCancel').click();assert.equal(await page.locator('#gameView').isVisible(),true);await page.locator('#exitGame').click();await page.locator('#confirmProceed').click();await page.locator('#gameView').waitFor({state:'hidden',timeout:60000});report.toolbarExit=await page.evaluate(()=>window.__v21Shutdown.at(-1));assert.equal(report.toolbarExit.shutdown.close.finalSaveFresh,true);assert.equal(report.toolbarExit.warning,undefined);
  report.checks.push('Real Alpine Assault terrain, live 1600 × 900 resolution, engine diagnostics, update blocked during play, cancellable match exit and final save flush');
  report.stage='Shutdown failure recovery';await launch();await game.evaluate(()=>{const bridge=window.CnCPort;bridge.persistFinalSaves=()=>Promise.reject(Error('Simulated final save failure'))});if(!await page.locator('#gameBar').isVisible())await game.locator('#viewport').press('F8');await page.locator('#exitGame').click();await page.locator('#gameView').waitFor({state:'hidden',timeout:60000});assert.match(await page.locator('#error').textContent(),/save/i);assert.equal((await library()).root,current.root);report.checks.push('Relaunch retains files; simulated save-flush failure closes game with an honest warning');
  assert.equal(report.errors.length,0);assert.equal(report.missing.length,0);report.status='passed';
 }catch(error){report.status='failed';report.failure=error.stack;process.exitCode=1;await page.screenshot({path:'output/playwright/v21-failure.png'}).catch(()=>{});console.log('FAIL',error.message,await page.locator('#error').textContent().catch(()=>''));}
 finally{clearInterval(timer);await fs.writeFile('.local/version-21-verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,failure:report.failure,checks:report.checks,errors:report.errors,missing:report.missing},null,2));await context.close();}
})();
