const {chromium}=require('playwright');
const fs=require('node:fs/promises');const path=require('node:path');const assert=require('node:assert/strict');
(async()=>{
 const report={version:'2.0.0',checks:[],errors:[],missing:[],started:new Date().toISOString(),scope:'Fresh Windows Chrome profile; actual local ZIP and RAR packages; real threaded-engine skirmish'};
 await fs.mkdir('output/playwright',{recursive:true});
 const ctx=await chromium.launchPersistentContext(path.resolve('.local/version-2-browser'),{channel:'chrome',headless:true,viewport:{width:1440,height:900}});
 const page=ctx.pages()[0]||await ctx.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.status()===404)report.missing.push(r.url())});
 const timer=setInterval(()=>console.log('V2',report.stage),20000);let game;
 const rpc=(command,payload={})=>game.evaluate(([command,payload])=>window.CnCPort.rpc(command,payload),[command,payload]);
 const wait=async(label,fn,predicate,timeout=60000)=>{let last;const deadline=Date.now()+timeout;while(Date.now()<deadline){last=await fn();if(predicate(last))return last;await page.waitForTimeout(300)}await fs.writeFile('.local/v2-last-state.json',JSON.stringify(last,null,2));throw Error(label+' timeout')};
 const library=()=>page.evaluate(()=>window.ZeroHAssetLibrary.installedLibrary());
 try{
  report.stage='Interface and theme';await page.goto('http://localhost:8093/');await page.waitForFunction(()=>typeof document.getElementById('nameForm').onsubmit==='function');
  if(!process.env.ZH_V2_GAME_ONLY){
  await page.evaluate(()=>localStorage.removeItem('zhweb-settings-v2'));await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.screenshot({path:'output/playwright/v2-entry-dark.png'});
  await page.locator('#themeToggle').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.locator('#themeToggle').click();report.checks.push('Dark default and remembered on/off theme');
  if(await page.locator('#entry').isVisible()){await page.locator('#name').fill('FieldTest');await page.locator('#nameForm button').click()}
  if(await page.locator('#lobby').isVisible()){await page.locator('#libraryDetails summary').click();await page.locator('#replaceLibrary').click();}
  await page.locator('#setup').waitFor({state:'visible'});
  assert.equal(await page.locator('.get-files a').count(),2);assert.match(await page.locator('.get-files a').first().getAttribute('href'),/1th6_GQ74/);
  await page.screenshot({path:'output/playwright/v2-setup-desktop.png'});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'output/playwright/v2-setup-mobile.png'});await page.setViewportSize({width:1440,height:900});
  await page.locator('#openSettings').click();await page.screenshot({path:'output/playwright/v2-settings.png'});await page.locator('#closeSettings').click();report.checks.push('Download links and responsive setup/settings');
  report.stage='Full local ZIP import';await page.locator('#archiveInput').setInputFiles('.local/packaging/Zero-Hour-Browser-English.zip');await page.locator('#lobby').waitFor({state:'visible',timeout:600000});let initial=await library();assert.equal(initial.archives.length,17);report.checks.push('Actual 1.09 GB compressed ZIP extracted, validated and installed (17 game archives)');
  await page.reload();await page.locator('#lobby').waitFor({state:'visible',timeout:30000});assert.equal((await library()).root,initial.root);report.checks.push('V1 storage namespace, commander and installed library survive reload');
  report.stage='Cancellation and malformed replacement';await page.locator('#libraryDetails summary').click();await page.locator('#replaceLibrary').click();await page.locator('#archiveInput').setInputFiles('.local/packaging/Zero-Hour-Browser-English.rar');await page.locator('#cancelImport').waitFor({state:'visible'});await page.locator('#cancelImport').click();await wait('Cancelled import',()=>page.locator('#chooseArchive').isEnabled(),Boolean);assert.equal((await library()).root,initial.root);
  await page.locator('#archiveInput').setInputFiles({name:'broken.zip',mimeType:'application/zip',buffer:Buffer.from('not a zip')});await wait('Bad archive rejection',()=>page.locator('#chooseArchive').isEnabled(),Boolean);assert.equal((await library()).root,initial.root);assert.match(await page.locator('#error').textContent(),/ZIP|archive/i);report.checks.push('Cancelled RAR and corrupt ZIP preserve the existing installation and allow retry');
  report.stage='Full local RAR5 import';await page.locator('#archiveInput').setInputFiles('.local/packaging/Zero-Hour-Browser-English.rar');await page.locator('#lobby').waitFor({state:'visible',timeout:900000});const rar=await library();assert.equal(rar.archives.length,17);assert.notEqual(rar.root,initial.root);report.checks.push('Actual 858 MB solid RAR5 with 512 MB dictionary streamed into OPFS, validated and installed');
  const staged=await page.evaluate(async()=>{const root=await navigator.storage.getDirectory();const d=await root.getDirectoryHandle('archive-staging');const names=[];for await(const [name] of d.entries())names.push(name);return names});assert.equal(staged.length,0);report.checks.push('Temporary extraction storage removed after success and cancellation');
  }else{const previous=JSON.parse(await fs.readFile('.local/version-2-verification.json'));report.checks.push(...previous.checks);report.resumedFrom=previous.started;await page.locator('#lobby').waitFor({state:'visible',timeout:30000});await wait('Stale extraction cleanup',()=>page.evaluate(async()=>{const d=await(await navigator.storage.getDirectory()).getDirectoryHandle('archive-staging');const files=[];for await(const [name]of d.entries())files.push(name);return files}),v=>v.length===0);report.checks.push('Temporary extraction storage removed after success, cancellation and restart');}
  if(await page.locator('#libraryDetails').getAttribute('open')===null)await page.locator('#libraryDetails summary').click();await page.locator('#verifyLibrary').click();await wait('Library verification',()=>page.locator('#verifyLibrary').isEnabled(),Boolean);
  await page.locator('#openSettings').click();await page.locator('#resetSettings').click();await page.locator('#closeSettings').click();
  report.stage='Real engine launch';await page.locator('#solo').click();await page.waitForFunction(()=>document.getElementById('gameFrame').contentWindow?.document.getElementById('loading')?.hidden===true,null,{timeout:180000});game=page.frames().find(f=>f.url().includes('/harness/game.html'));await wait('Skirmish options',()=>rpc('queryWindowByName',{name:'SkirmishGameOptionsMenu.wnd:ButtonStart'}),r=>r.result?.clickable===true);
  await wait('Automatic toolbar hide',()=>page.locator('#gameView').getAttribute('class'),s=>s?.includes('toolbar-hidden'));
  await game.locator('#viewport').press('F8');assert.equal(await page.locator('#gameBar').isVisible(),true);await page.locator('#gameSettings').click();await page.locator('#resolution').selectOption('1024x768');await wait('Live resolution',()=>rpc('threadedStatus'),r=>r.status?.engineDisplaySize?.width===1024);await page.locator('#closeSettings').click();report.checks.push('F8 restores the hidden toolbar and settings apply real 1024 × 768 engine resolution');
  await wait('Skirmish menu recreated after resolution',()=>rpc('queryWindowByName',{name:'SkirmishGameOptionsMenu.wnd:ButtonStart'}),r=>r.result?.clickable===true);
  await rpc('realEngineSetSkirmishMap',{mapName:'maps/alpine assault/alpine assault.map'});await rpc('realEngineSetSkirmishLocalTemplate',{templateName:'FactionGLA'});await rpc('clickWindowByName',{name:'SkirmishGameOptionsMenu.wnd:ButtonStart'});
  report.stage='Real battlefield and mouse edges';const active=await wait('Battlefield',()=>rpc('realEngineFrame',{frames:1}),r=>r.frame?.clientState?.gameplay?.inGame===true&&!r.frame?.clientState?.gameplay?.loadingMap&&r.frame?.clientState?.gameplay?.objectCount>0,180000);report.renderer=(await rpc('threadedStatus')).status?.graphics?.renderer;report.checks.push('RAR-imported retail data boots the real skirmish battlefield');
  await wait('Settled HUD',()=>rpc('realEngineFrame',{frames:1}),r=>r.frame?.clientState?.controlBarWindows?.parent?.y<768,90000);
  await game.locator('#viewport').press('F8');if(await page.locator('#gameBar').isVisible())await page.locator('#hideToolbar').click();
  const camera=async()=> (await rpc('realEngineFrame',{frames:1})).frame?.clientState?.view?.position;
  const edgeEvidence=[];
  for(const direction of ['left','right','top','bottom']){
    const b=await game.locator('#viewport').boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/3);await page.waitForTimeout(300);const before=await camera();
    const points={left:[b.x-5,b.y+b.height/3],right:[b.x+b.width+5,b.y+b.height/3],top:[b.x+b.width/2,b.y+1],bottom:[b.x+b.width/2,b.y+b.height-1]};
    await page.mouse.move(...points[direction]);await page.waitForTimeout(1100);const after=await camera();edgeEvidence.push({direction,before,after,distance:Math.hypot(after.x-before.x,after.y-before.y)});
    await page.mouse.move(b.x+b.width/2,b.y+b.height/3);
  }
  report.edges=edgeEvidence;assert.ok(edgeEvidence.every(e=>e.distance>1),'All four edges must move the real camera');report.checks.push('Real camera displacement at all four edges, including outside-canvas letterboxing');
  report.stage='Live 16:9 resolution and native mouse selection';await game.locator('#viewport').press('F8');await page.locator('#gameSettings').click();await page.locator('#resolution').selectOption('1600x900');await wait('Mid-match resize',()=>rpc('threadedStatus'),r=>r.status?.engineDisplaySize?.width===1600);await page.locator('#closeSettings').click();
  const builder=(await rpc('queryDrawables')).drawables.allDrawables.find(o=>o.localOwned&&o.kindOf?.dozer);assert.ok(builder,'Original builder exists');await rpc('agentCameraLookAt',{x:builder.worldPos.x,y:builder.worldPos.y,z:0});
  await page.waitForTimeout(1500);let worker;for(const offset of [-12,-20,0]){const draws=(await rpc('queryDrawables')).drawables.drawables;worker=draws.find(o=>o.localOwned&&o.kindOf?.dozer&&o.onScreen);assert.ok(worker,'An on-screen worker is required for mouse verification');const b=await game.locator('#viewport').boundingBox();report.mouseProbe={worker,b,display:(await rpc('threadedStatus')).status?.engineDisplaySize};await page.mouse.click(b.x+worker.screenPos.x*b.width/1600,b.y+(worker.screenPos.y+offset)*b.height/900);await page.waitForTimeout(1000);report.selection=await rpc('querySelection');if(report.selection.result?.selected?.some(o=>o.id===worker.id))break;}
  assert.ok(report.selection.result?.selected?.some(o=>o.id===worker.id),'Mouse must select the actual worker');const b=await game.locator('#viewport').boundingBox();
  await page.mouse.click(b.x+(worker.screenPos.x+70)*b.width/1600,b.y+(worker.screenPos.y+60)*b.height/900,{button:'right'});await wait('Mouse movement',()=>rpc('queryDrawables'),r=>{const o=r.drawables.drawables.find(o=>o.id===worker.id);return o&&Math.hypot(o.worldPos.x-worker.worldPos.x,o.worldPos.y-worker.worldPos.y)>20});report.checks.push('Live 1600 × 900 match reflow preserves real mouse selection and movement');
  const shot=await rpc('screenshot');if(shot.screenshot?.dataUrl)await fs.writeFile('output/playwright/v2-battlefield.png',Buffer.from(shot.screenshot.dataUrl.split(',')[1],'base64'));
  await game.locator('#viewport').press('F8');await page.locator('#gameSettings').click();await page.locator('#edgeScroll').uncheck();await page.locator('#closeSettings').click();const rb=await game.locator('#viewport').boundingBox();await page.mouse.move(rb.x+rb.width/2,rb.y+rb.height/3);const before=await camera();await page.mouse.move(rb.x+1,rb.y+rb.height/3);await page.waitForTimeout(1100);const after=await camera();assert.ok(Math.hypot(after.x-before.x,after.y-before.y)<1);report.checks.push('Edge scrolling can be disabled');
  report.stage='Fullscreen and clean exit';if(!await page.locator('#gameBar').isVisible())await game.locator('#viewport').press('F8');await page.locator('#fullscreen').click();await page.waitForFunction(()=>!!document.fullscreenElement);await game.locator('#viewport').press('Alt+Enter');await page.waitForFunction(()=>!document.fullscreenElement);if(!await page.locator('#gameBar').isVisible())await game.locator('#viewport').press('F8');await page.locator('#exitGame').click();await page.locator('#confirmProceed').click();await page.locator('#gameView').waitFor({state:'hidden',timeout:45000});report.checks.push('Fullscreen shortcut and protected clean exit');
  assert.equal(report.errors.length,0);assert.equal(report.missing.length,0);report.status='passed';
 }catch(e){report.status='failed';report.failure=e.stack;process.exitCode=1;await page.screenshot({path:'output/playwright/v2-failure.png'}).catch(()=>{});console.log('ERROR',e.message,await page.locator('#error').textContent().catch(()=>''))}
 finally{clearInterval(timer);report.checks=[...new Set(report.checks)];await fs.writeFile('.local/version-2-verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,failure:report.failure,checks:report.checks,errors:report.errors,missing:report.missing},null,2));await ctx.close()}
})();
